{-# LANGUAGE QuasiQuotes #-}

module Postgres.Init where

import Data.String.Interpolate (i)
import Hasql.Session qualified
import Postgres.Details (Schema (..), TableName (..))
import Relude

initTaskTable :: Schema -> TableName -> Hasql.Session.Session ()
initTaskTable (Schema schema) (TableName table) =
  Hasql.Session.sql
    [i|
    create schema if not exists "#{toText schema}";
    create table if not exists "#{toText schema}"."#{toText table}" (
      "created_at" timestamptz not null,
      "updated_at" timestamptz not null,
      "id" bigint generated by default as identity primary key,
      "is_completed" bool not null,
      "description" text not null,
      "due" timestamptz,
      "remind_at" timestamptz,
      "repeat_after" text,
      "parent" bigint,
      "tags" text);
    |]
